apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dhbw-seminarbeit-receivedata
  name: dhbw-seminarbeit-receivedata
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dhbw-seminarbeit-receivedata
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dhbw-seminarbeit-receivedata
    spec:
      containers:
      - env:
        - name: EVENT_BUS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: EVENT_BUS_ENDPOINT
              name: env
        image: dhbw-seminarbeit-receivedata
        imagePullPolicy: ""
        name: dhbw-seminarbeit-receivedata
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
