apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dhbw-seminarbeit-receivedata 
  name: dhbw-seminarbeit-receivedata
spec:
  type: NodePort
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
  selector:
    app.kubernetes.io/name: dhbw-seminarbeit-receivedata
status:
  loadBalancer: {}
